export default function TermsPage() {
    return (
        <div className="min-h-screen pt-32 pb-20 bg-background">
            <div className="container mx-auto px-4 max-w-3xl">
                <div className="mb-16">
                    <h1 className="text-4xl md:text-5xl font-sans font-bold tracking-tight mb-4">Terms of Service</h1>
                    <p className="text-muted-foreground">Last updated: February 27, 2026</p>
                </div>

                <div className="prose prose-invert max-w-none prose-p:text-muted-foreground prose-p:leading-relaxed prose-headings:text-foreground">
                    <h2>1. Acceptance of Terms</h2>
                    <p>
                        By accessing and using the software, desktop applications, websites, APIs, and services (collectively the "Services") provided by TiltedPrompts ("we," "us," or "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use our Services.
                    </p>

                    <h2>2. Local Software Execution (TiltedVoice)</h2>
                    <p>
                        Our standalone applications, specifically TiltedVoice, are designed as completely offline, local-first tools. By utilizing these tools:
                    </p>
                    <ul>
                        <li>You accept that all processing (including speech-to-text inference) happens on your local hardware.</li>
                        <li>You recognize that TiltedPrompts holds no responsibility for the accuracy, retention, or security of transcripts generated locally on your machine.</li>
                        <li>You are responsible for obtaining the necessary hardware resources required to run the open-source inference models (such as Whisper).</li>
                    </ul>

                    <h2>3. Account Registration & Security</h2>
                    <p>
                        To use our cloud-based managed Model Context Protocol (MCP) infrastructure, you must register for an account. You agree to provide accurate, current, and complete information during the registration process. You are entirely responsible for maintaining the confidentiality of your API keys and account passwords.
                    </p>

                    <h2>4. API Usage and Rate Limiting</h2>
                    <p>
                        Our cloud Services (TiltedMCP, TiltedVani endpoints) are subject to rate limits. We reserve the right to throttle, suspend, or terminate access for accounts that attempt to bypass these limits or that exhibit usage patterns harmful to our infrastructure.
                    </p>

                    <h2>5. Intellectual Property</h2>
                    <p>
                        The desktop applications, web interfaces, backend code, and compiled software provided by TiltedPrompts remain our exclusive property. The underlying open-source machine learning models (e.g., faster-whisper, Sarvam AI models) retain their respective licenses. You retain absolute ownership over all content (audio, text, configurations) parsed through or generated by your usage of our tools.
                    </p>

                    <h2>6. Limitation of Liability</h2>
                    <p>
                        In no event shall TiltedPrompts be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Services; or (ii) any conduct or content of any third party on the Services.
                    </p>

                    <h2>7. Changes to Terms</h2>
                    <p>
                        We reserve the right to modify these terms at any time. We will provide notice of significant changes by updating the date at the top of this page. Your continued use of the Services following any changes indicates your acceptance of the new terms.
                    </p>

                    <hr className="my-12 border-border" />
                    <p className="text-sm">
                        If you have any questions about these Terms, please contact us at legal@tiltedprompts.com
                    </p>
                </div>
            </div>
        </div>
    );
}
